# CI Workflow: Biome JS | Mobile App
#
# This workflow automates the process of checking code style using Biome.
# It is triggered on push events to the `app` folder from any branch.
#
# Permissions:
# - contents: read
#
# Jobs:
# 1. **style-checker**: This job checks the code style using Biome.
#    - Steps:
#      1. Checkout the repository.
#      2. Setup Node.js environment.
#      3. Install dependencies and run Biome check.

name: "CI: Biome JS | Mobile App"

on:
  push:
    paths:
      - app/**

permissions:
  contents: read

jobs:
  style-checker:
    name: Style Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: Install dependencies and run biome
        run: |
          cd app
          npm install
          npm run biome:check
          