# CI Workflow: Biome JS | Functions
#
# This workflow automates the process of checking code style using Biome.
# It is triggered on push and pull request events to the main branch.
#
# Jobs:
# 1. **style-checker**: This job checks the code style using Biome. It installs the necessary
#    dependencies and runs the `biome:check` script defined in the `package.json` file.

name: "CI: Biome JS | Functions"

on:
  push:
    paths:
      - functions/**

permissions:
  contents: read

jobs:
  # Job to check code style using Biome
  style-checker:
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Step to setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: functions/package-lock.json
      # Step to install dependencies and run Biome check
      - name: Install dependencies and run biome
        run: |
          cd functions
          npm install
          npm run biome:check
