name: "CI: EAS Dev Build"

on:
  push:
    paths:
      - app/**

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  GOOGLE_SERVICE_INFO: ${{ secrets.GOOGLE_SERVICE_INFO }}
  GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
  FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
  GOOGLE_AUTH_CLIENT_ID: ""

jobs:    
  build-dev-android:
    name: Build Expo Developer Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Create GoogleService-Info.plist
        working-directory: ./app
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_INFO_CONTENT }} | base64 --decode > GoogleService-Info.plist
      - name: Create google-services.json
        working-directory: ./app
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_JSON_CONTENT }} | base64 --decode > google-services.json
      - name: Install dependencies
        working-directory: ./app
        run: npm install
      - name: Build Android
        working-directory: ./app
        run: eas build --platform android --profile dev:virtual --local --output ${{ github.workspace }}/android-dev.apk
      - name: Upload Android APK
        id: android
        uses: actions/upload-artifact@v4
        with:
          name: Android Dev APK
          path: ${{ github.workspace }}/android-dev.apk
      - name: Build iOS
        working-directory: ./app
        run: eas build --platform ios --profile dev:virtual --local --output ${{ github.workspace }}/ios-dev.ipa
      - name: Upload iOS IPA
        id: ios
        uses: actions/upload-artifact@v4
        with:
          name: iOS Dev IPA
          path: ${{ github.workspace }}/ios-dev.ipa
      - name: Comment on PR
        if: ${{ !contains(github.ref_name, 'main') }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-tag: dev-build-link-comment
          message: |
            ### Android Dev Build
            [Android Dev Build](${{ steps.android.outputs.artifact-url }})

            ### iOS Dev Build
            [iOS Dev Build](${{ steps.ios.outputs.artifact-url }})
          